### ISSUE TITLE
[help] 行距。

### ISSUE THREAD

**Issue by prowaynes** [ZQF-ReVN/RxPJADV#1]
非常感谢你们的辛勤工作。我在查看内存转储时发现，文本中每个字母之间多了一个空格。我一直在试图找出造成这种情况的原因，所以请告诉我应该从哪个方向查找信息。
![1](https://github.com/Dir-A/PJADV_Tools/assets/9343543/717d0c09-ee6e-49e6-b277-c4fbed4d7a01)
![2](https://github.com/Dir-A/PJADV_Tools/assets/9343543/68da2fa7-6710-4081-8a3b-cfa1dda382f0)

**Comment by Dir-A** [comment]
引擎默认设置为字体间距固定，单字节字符宽度绘制宽度会减半，像是 ‘a’:0x41 这种，所以英文可以正常显示，我还没有分析完字体绘制的全部流程，引擎应该支持可变间距，总得来说间距可以被修复，不是主要的问题

最主要的问题是，这个引擎的文本框一般默认只能显示3行，暂时没找到修改的方法，也没有完整的脚本反编译工具，这意味不能够直接增加文本页数，所以唯一的办法是缩小字体来放下更多的俄文单词，但是我测试过，三行并不能放下多少俄文字母，大概100个左右（包括括号）

**Comment by prowaynes** [comment]
这不是主要问题，因为您可以用不同的方式来解释文本。编辑器可以处理这个问题。他们可以将长句改写成短句，而不会失去意义。主要问题是固定间隔，我有一个程序的例子，它被删除了，但问题是它不能与该游戏一起使用，因为它与另一个游戏的 EXE 绑定。
以下是翻译实施的示例  Taiyou no Promia
 https://vndb.org/v4259
[рус.zip](https://github.com/Dir-A/PJADV_Tools/files/14291059/default.zip)
但在这款游戏中，俄语最初可以正常使用，唯一的问题是由 promia_ru.exe 修正的时间间隔，我还不明白他们是如何做到这一点的，以及如何重复这一点。
![image](https://github.com/Dir-A/PJADV_Tools/assets/9343543/39673c8b-ff45-432d-9ead-8a0530927ce6)

**Comment by Dir-A** [comment]
好吧，我稍微看了一下间距的控制，总得来说，要直接修改间距很麻烦，每个游戏都需要重新找地址，但游戏对单字节显示会间距减半，显示俄文勉强能看。

我看了 Taiyou no Promia 的实现，它修补了很多地方，我不能向你展示它的修补方法，因为它需要了解引擎的内部的运行原理，我可以写在这，但会很长，很浪费时间，也很难在其它游戏上复现，简单来说，就是写了你也不一定能懂。

所以我选择向你说明一个简单的方法，它可以显示出可接受范围内的俄文字体，而不需要过多的修改

第一步应该先把 引擎的字体渲染方式切换的GDI，就像我在这篇文章中说的那样[实例修改](https://github.com/Dir-A/Dir-A_Essays_MD/blob/main/Reverse/%5BPJADV%5D%20%E5%AD%97%E4%BD%93%E6%B8%B2%E6%9F%93%E5%88%86%E6%9E%90/%5BPJADV%5D%20%E5%AD%97%E4%BD%93%E6%B8%B2%E6%9F%93%E5%88%86%E6%9E%90.md#%E5%AE%9E%E4%BE%8B%E4%BF%AE%E6%94%B9)

切换好后就可以修改CreateFont的参数，比如charset，来控制编码了，否则游戏默认是从fontdata.dat中加载字体图形的

nop fontdata.dat加载
![2](https://github.com/Dir-A/PJADV_Tools/assets/79064817/925db528-0e4d-4042-9520-ae6027b72349)


现在可以修改 CreateFont的charset为0xCC ，这是俄文的chaeset，并nop掉游戏的内置字体切换分支，同时修改字体名为Segoe UI
![3](https://github.com/Dir-A/PJADV_Tools/assets/79064817/04ff5ab9-873d-4ecf-a7a6-90d14c2693b3)


然后要找到日文的边界检查 ，搜索常量0x9F，找到检查的代码，nop掉
![1](https://github.com/Dir-A/PJADV_Tools/assets/79064817/ccabbb70-bf91-4271-87fa-42e42b47fbc7)

现在引擎就可以读取cp1251编码的文本
![4](https://github.com/Dir-A/PJADV_Tools/assets/79064817/54267ab6-689b-40df-9339-74cfc8107f07)
可以发现，其实它还是固定间距的，但这个是我能给你介绍的最简单的修改方法了。

**Comment by prowaynes** [comment]
非常感谢。
https://github.com/pkuislm/PJADV-Font-Maker
我看到有人写了一个字体创建实用程序，但我还没怎么学过，我需要在更改之前找出游戏使用的字体。

**Comment by prowaynes** [comment]
今天我再次尝试修改文件，得到的结果是这样的： 

![2024-02-16 11 58 02](https://github.com/Dir-A/PJADV_Tools/assets/9343543/a26201d7-d2a5-4bc3-8cda-8a22ee315672)

我首先比较了文件，发现类似的分支（在 promia 中）并不在 tarareba 游戏中。

![2024-02-16 14 15 39](https://github.com/Dir-A/PJADV_Tools/assets/9343543/97cb7239-a5f5-4255-ac10-a603e4148ab8)

当我删除搜索常数 0x9F 时，情况变得更糟了。

![2024-02-16 14 41 18](https://github.com/Dir-A/PJADV_Tools/assets/9343543/f3247b58-2c98-44ec-952b-dad23f61b017)

但无济于事。

![2024-02-16 14 49 08](https://github.com/Dir-A/PJADV_Tools/assets/9343543/eba67959-2162-4346-9d0c-511ba990507b)

但我决定再重复一遍，首先我使用了之前的版本，其中字母之间有空格，然后删除了搜索常数 0x9F（因为我之前忽略了它）。

[resource.zip](https://github.com/Dir-A/PJADV_Tools/files/14309636/resource.zip)


我还会添加我用来打包文本的实用程序，也许这就是问题所在......还有 exe，请看一下。
https://vndb.org/v18749 - 同时附上游戏链接。谢谢。

**Comment by Dir-A** [comment]
你应该遵循我说的步骤，首先你应该把游戏的渲染方式从 `字体文件渲染` ，切换到从 `GDI渲染` ，就和我之前附上的文章中说的那样

这个游戏默认是从fontdata.dat文件中获取某个字符的图形，然后把这个图形贴图到文本框上，如果是这种渲染方式，不管你如何修改，都不可能正确显示，因为fontdata.dat文件的字符图形数量是有限的，并不能显示所有字符，而且默认是SJIS编码的

所以你的第一步应该是把字体的渲染方式切换到GDI，也就是抛弃fontdata.dat文件，我们并不需要fontdata.dat也不需要去修改它。

只有你完成了文本渲染方式的切换，一切才能够继续

这是我修改好的文件，你可用使用它，并对比区别，exe是游戏的原始版本，并没有安装更新补丁
[promia_nod.zip](https://github.com/Dir-A/PJADV_Tools/files/14309796/promia_nod.zip)

**Comment by prowaynes** [comment]
非常感谢。我不明白如何切换渲染模式，我会再看看这篇文章的。 我以为绑定是（图片），但那个游戏里没有，所以我很困惑。
![image](https://github.com/Dir-A/PJADV_Tools/assets/9343543/e8fc9f21-7869-4393-8201-d93a4549e70f)

**Comment by Dir-A** [comment]
我关了这个issue，如果你有任何问题可以重新打开

**Comment by prowaynes** [comment]
![image](https://github.com/Dir-A/PJADV_Tools/assets/9343543/8815f8c1-7b8a-4111-84ef-30e5e23a29b8)
下午好，到目前为止，我使用小说 tarareba 实现了这些结果，我想我没有正确指定字体，能否请您看看当前文件的字体。https://vndb.org/v18749
文本以 CP1251 编码
谢谢

[tarareba-test-12-rus.zip](https://github.com/Dir-A/PJADV_Tools/files/15223716/tarareba-test-12-rus.zip)

**Comment by prowaynes** [comment]
![image](https://github.com/Dir-A/PJADV_Tools/assets/9343543/3b56964e-1be1-480a-a114-0da78e2ad77e)

我还试着移动字体说明并对其进行调整，这是我得到的最好的结果。但还有一个问题，就是空格过大，字母 (ы) 或 (ж) 会被切掉一些......如果您尝试将 lfWidth 增加到 10 以上，文本会立即变粗，并立即导致......恐怖。

![image](https://github.com/Dir-A/PJADV_Tools/assets/9343543/98fb632e-53e2-4508-b532-5c6d8f8b3cb4)

我移动了下面的一些说明，这样更改数值就不会破坏代码的完整性。

[tarareba-test-27-rusbad.zip](https://github.com/Dir-A/PJADV_Tools/files/15238552/tarareba-test-27-rusbad.zip)

**Comment by Dir-A** [comment]
[tarareba_ru.zip](https://github.com/Dir-A/PJADV_Tools/files/15238696/tarareba_ru.zip)

你基本上是正确的
我添加了两项修改

1、字体名称改为 Cyrillic 似乎拥有更好的显示效果
2、移除读取textdata.bin的解密过程，因为garbro解密了textdata.bin，所以为了让游戏能够直接读取没有加密的textdata.bin，我们需要阻止程序再次解密

你之所以有显示问题，我的猜测是你导入了错误的编码到textdata.bin，你可以查看我修改过的textdata.bin文件
![QQ截图20240508010507](https://github.com/Dir-A/PJADV_Tools/assets/79064817/988589cd-71e4-4b0b-aa50-29ac4c154bc9)

**Comment by prowaynes** [comment]
晚安，我决定重新研究翻译问题。
但我遇到了一个问题。
首先，我将字体设置为 Arial，但字母仍然跳来跳去。
![Screenshot 2024-09-27 045132](https://github.com/user-attachments/assets/be1a5ac6-39c6-4d2b-a4b3-e7780eecb00c)
以下是测试结果
![Screenshot 2024-09-27 045341](https://github.com/user-attachments/assets/5add38cb-decc-4e68-8c90-1f3ecd3f0db7)
而你的回收副本根本拒绝显示文字。
![Screenshot 2024-09-27 045244](https://github.com/user-attachments/assets/2c035730-515f-4b5c-8f48-8ca73336ebd4)
我使用您的工具对文本进行了转码。
![Screenshot 2024-09-27 045721](https://github.com/user-attachments/assets/a739e570-8834-444f-89bf-ea504c8b37da)
我已经尝试了各种可能的方法来影响 hdc，但都无济于事。 谢谢
[tarareba-test-12-rus2.zip]
(https://github.com/user-attachments/files/17157339/tarareba-test-12-rus2.zip)

**Comment by Dir-A** [comment]
let's switch to English first 

## Background
for the PJADV engine it has two ways of rendering fonts, 
get graphic data from gdi (Windows system api),
or 
get graphic data from fontdata.xxx file(in the archive file),

If get graphic data from gdi, this means we can tweak gdi's parameters to display characters from different languages.
If get graphic data from fontdata.xxx, the characters that can be displayed depend on the data stored in fontdata.xxx.

the engine can support a mix of both(for example, msg text use gdi and log text use fontdata), which can be controlled in the script, but the script has already been compiled and we can't easily modify it.

for this game(太陽のプロミア), it should be gdi, this means that we only need to change the relevant parameters of gdi to display Russian text.

## GDI Font Object Create
first we need to change the charset of GDI.CreateFontIndirectA,
0x80(SHIFTJIS_CHARSET) -> 0xCC(RUSSIAN_CHARSET)
![1](https://github.com/user-attachments/assets/8460baa3-3997-43d2-ac12-a140ae6d3b1e)
then change the font to Cyrillic or font name already installed on your system
![2](https://github.com/user-attachments/assets/0d7790f7-7660-45d1-9396-aeeb0e362263)
note that we can find a place that skips GDI.CreateFontIndirectA, which is part of the logic reserved for fontdata
but we don't want that to happen, because then our changes to gdi would be invalidated
so just nop
![3](https://github.com/user-attachments/assets/53c9a04a-049d-481b-9a74-11912ad8f0f0)
oK we've finished modifying the gdi parameters

## Range Check
we know that sjis is a dbcs encoding which is a double byte encoding, it has a single byte part, i.e. 0-7F part, or if a byte is less than 0x81 then we can consider it as a single byte representation of the character, otherwise the character needs two bytes to represent it.
so we can find this place, which is to determine whether a character is double-byte or single-byte in sjis
however, Russian generally uses a single-byte encoding i.e. windows-1251
and for this game it will set the width of double-byte encoded characters to unit 1, and halve the width when it finds out it's a single-byte,
sjis is able to contain all Russian characters, but these Russian characters are double-byte encoded, so that's why, when you write Russian in sjis encoding, it has spaces between words,
now we are going to use Windows-1251 encoding, which is single-byte, and since there is no way for 0-7f to represent all Russian characters, we need to use the x80-0xFF part, but sjis will have double-byte characters present in this part, and if we don't change the range of detection, then this will cause problems,
so we can nop out the code, leaving xor eax, eax, which means that the return value will always be 0, i.e., it means that it will always be a single-byte read.
![4](https://github.com/user-attachments/assets/09b16fff-8953-4c6c-94f7-4d459b86dbde)
![5](https://github.com/user-attachments/assets/d06b83b0-2228-4ab5-a3f4-841efa07232a)

now we can save it.
![6](https://github.com/user-attachments/assets/53a48aea-a75c-46b8-9dc2-b9c076280b11)

## Import Texts
go to https://github.com/Dir-A/ReVN to download PJADV-Tools-x64-Release.zip

first we use PJADV_Pack_V2_Editor.exe to unpack archive.dat
![7](https://github.com/user-attachments/assets/73ce0596-9079-4b8e-a53e-d843efd4425a)
then find scenario.dat and textdata.bin file
we can see that textdata.bin is encrypted
![8](https://github.com/user-attachments/assets/35cf93b6-1d16-4348-b485-b12d8a169034)
use PJADV_TextDataDat_Cryptor.exe to decrypt it
![9](https://github.com/user-attachments/assets/c3e3fe0f-d6b1-4690-90a7-c76b57015d50)

now we can use PJADV_Text_Editor.exe to extract the text
![a](https://github.com/user-attachments/assets/14f6491e-4ceb-4649-a31f-2971fab984ac)
modify, then import
![b](https://github.com/user-attachments/assets/d48a877d-f1ad-4275-bb9e-e5ace08a54cf)
note that the codepage is 1251
![c](https://github.com/user-attachments/assets/3ae6795f-a8a2-4726-84ee-cc34606c318f)
then you will get a lot of warnings, this is because Japanese characters are not encoded with windows-1251
this is normal, when you translate the whole text you don't have this problem anymore
![d](https://github.com/user-attachments/assets/ae3f79da-87b3-4d5f-b745-bf916268dde3)

now we need to encrypt the textdata.bin.dec.new back
![e](https://github.com/user-attachments/assets/a927e009-e3d7-4dea-a744-a8e5f3701611)

okay, copy it to the game directory and restore the filename
![f](https://github.com/user-attachments/assets/b1aee918-6159-44a1-8b97-e5e084062711)

you can see that it's already displaying properly, 
![g](https://github.com/user-attachments/assets/ece18b12-3ae3-4a96-8cb9-97ec6e80f5f8)

## A Few More Things
but we still need to fix a few things
like show more lines(just 3 lines now), adjust font size(if you want), make bold(look better)
I'll give you three addresses in scenario.dat
```
scenario.dat: 0x244F38 -> character name font
scenario.dat: 0x244F64 -> msg font
scenario.dat: 0x246D7C -> log font
```
How is it used?
https://github.com/ZQF-ReVN/RxPJADV/issues/3
https://github.com/ZQF-ReVN/RxPJADV/blob/main/etc/PJADV.md#command

**Comment by Dir-A** [comment]
let's talk about what to do if a game is locked out of getting graphics data from fontdata.

In short there's a function that loads all the fontdata files when the game starts, then you can select the fonts in the script, but you can't easily modify the script, that's a fact.

but if I give you the relevant address, it's possible, like 
```
0x0300000B [create font / msg fon][太陽のプロミア]
        0B000003  -> opcode
        00000000  -> font id
        F1000000  -> text box x
        04020000  -> text box y
        2C010000  -> text box width
        1E000000  -> text box heigh
        1E000000  -> char heigh
        1E000000  -> char width
        1E000000  -> text line space
        FFFFFF00  -> unknown
        01000000  -> font type // 1,2,3,4 -> GDI | other -> fontdata.xx
```

just change the font type, then you can switch to gdi
but it's a little hard to find this, If you don't know how this works

so here's an easy way to do it

we've nopped a jump code where we've changed the Charset, 
why? this is because the font type may be 14 or 18 or something like that, if so, it will skip CreateFont, which will result in a failure to get the graphic data from gdi.
that's the first step we have to take.

The other step is to search for the string %s%.3d in the exe and find the function header, then find the place where this function is called and nop it off so that it doesn't load the fontdata
![QQ20240928-204312](https://github.com/user-attachments/assets/60b67bb7-53eb-47b1-a4d0-57f88bc1f48f)
![QQ20240928-204329](https://github.com/user-attachments/assets/bba228a4-d1d4-42e4-a5ad-97c96ed606b3)
